---
- hosts: all
  #user: root
  become: yes
  gather_facts: yes
  connection: ssh
 
  tasks:
  
    - name: creating the docker resources using docker-compose
      ansible.builtin.command: docker-compose up --build -d 
      notify: listing containers
  handlers:

    - name: listing containers
      ansible.builtin.command: docker ps 
