services:
  web1:
     
    image: gudditi/resume:latest
    container_name: webapp1
    ports:
      - '80:80'
    networks:
      - network-example
  web2:

    build:
      dockerfile: Dockerfile
      context: .
    container_name: webapp2
    ports:
      - '90:80'
    networks:
      - network-example
    depends_on:
      - web1



networks:
  network-example:
    external: true
