
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresume
spec:
  selector:
    matchLabels:
      app: myresume
  template:
    metadata:
      labels:
        app: myresume
    spec:
      containers:
      - name: myresume
        image: gudditi/myresume:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myresume
spec:
  type: NodePort
  selector:
    name: myresume
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31143

