name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gudditi/resume:latest${{ github.run_number }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image with build number tag
        run: docker push gudditi/resume:latest${{ github.run_number }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull gudditi/resume:latest${{ needs.build.outputs.tag }}

      - name: Run tests
        run: |
          # Run your test commands against the pulled image
