name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gudditi/resume:latest${{ github.run_number }}

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image gudditi/resume:latest --exit-code 1 --format json > trivy-results.json

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v2
      with:
        name: trivy-results
        path: trivy-results.json    
      
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image with build number tag
      run: docker push gudditi/resume:latest${{ github.run_number }}
